# Generated by Django 3.2.5 on 2021-07-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinnanoVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='やりたいこと')),
                ('with_who', models.CharField(choices=[('0', 'ひとりで'), ('1', '恋人と'), ('2', '友達と'), ('3', '家族と'), ('4', '見知らぬ誰かと')], max_length=30, verbose_name='誰と')),
                ('cost', models.IntegerField(verbose_name='およその金額')),
                ('time_required', models.CharField(choices=[('0', '1時間以内'), ('1', '2~3時間'), ('2', '半日'), ('3', '1日'), ('4', '1伯以上')], max_length=30, verbose_name='所要時間')),
                ('published', models.BooleanField(default=False, verbose_name='公開')),
                ('yaritai', models.IntegerField(default=0, verbose_name='やってみたい')),
                ('copied', models.IntegerField(default=0, verbose_name='コピーされた数')),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(to='my_vacation.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
