# Generated by Django 3.2.5 on 2021-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minnanovacation',
            name='published',
            field=models.BooleanField(default=True, verbose_name='公開'),
        ),
    ]
