# Generated by Django 3.2.5 on 2021-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vacation', '0003_alter_minnanovacation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minnanovacation',
            name='genre',
        ),
        migrations.AlterField(
            model_name='minnanovacation',
            name='time_required',
            field=models.CharField(choices=[('0', '1時間以内'), ('1', '2~3時間'), ('2', '半日'), ('3', '1日'), ('4', '1泊以上')], max_length=30, verbose_name='所要時間'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
