# Generated by Django 3.2.5 on 2021-07-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vacation', '0004_auto_20210724_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minnanovacation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='minnanovacation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
